@echo off
echo Cleaning up...
if exist test.py del test.py
echo Initializing git...
git init
echo Setting remote origin...
git remote add origin https://github.com/mohithadap-dotcom/Nagar-Netra-Team-Npcs.git
echo Adding files...
git add .
echo Committing changes...
git commit -m "Initial commit: Nagar-Netra project structure"
echo Pushing to main branch...
git push -u origin main
echo Done!
